### ISSUE TITLE
secure backend with Token Introspection is not working

### ISSUE THREAD

**Issue by Entrio** [ory/examples-archive#11]
When attempting to access **/articles/secure-backend-with-oauth2-token-introspection** with a valid token, the following error is presented:[gist](https://gist.github.com/Entrio/ecd62eacb6b8e93c214b5a191bbff622)

Token works on other endpoints just fine.
Image attached
![image](https://user-images.githubusercontent.com/539095/41553037-660681e4-7352-11e8-85f3-7695600d790b.png)

The logfile:
`GET /articles/secure-backend-with-oauth2-token-introspection 304 462.220 ms - -`

**Comment by aeneasr** [comment]
Really needs an automated test suite... :D Seems like it's probably just some wrong URL

**Comment by aeneasr** [comment]
This is fixed on master now
