### ISSUE TITLE
start-full-stack does not bootstrap properly on Windows 10 (CR/LF issue)

### ISSUE THREAD

**Issue by MilesDuke-Keysight** [ory/examples-archive#13]
Configuration: Docker for Windows 10, git bash, gnu make.exe

After running "make start-full-stack", the docker containers build and start running, but the various curl commands return no records for clients, rules, or policies.

The docker log for the configurator container shows that various scripts in the scripts folder fail to run owing to carriage-returns injected by git.

The resolution is fairly simple -- add a .gitattributes file to disable CR/LF translation:

    # Never do crlf translation of bash scripts
    *.sh -crlf

I can submit a PR with this change, if desired.

**Comment by aeneasr** [comment]
Yes, please submit a PR!
