### ISSUE TITLE
hydra.exe error while loading shared libraries ( hydra from src at win32 )

### ISSUE THREAD

**Issue by aburayyanjeffry** [ory/examples-archive#25]
I've successfully compiled hydra at Win32 system by using git-bash console. I used this steps to compile the hydra

`
go get -d -u github.com/ory/hydra
cd $(go env GOPATH)/src/github.com/ory/hydra
HYDRA_LATEST=$(git describe --abbrev=0 --tags)
git checkout $HYDRA_LATEST
GO111MODULE=on go install \
    -ldflags "-X github.com/ory/hydra/cmd.Version=$HYDRA_LATEST -X github.com/ory/hydra/cmd.BuildTime=`TZ=UTC date -u '+%Y-%m-%dT%H:%M:%SZ'` -X github.com/ory/hydra/cmd.GitHash=`git rev-parse HEAD`" \
    github.com/ory/hydra
`

after that
`
$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 98 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

`

then when I executed the hydra.exe it gave me this error
`
x@x MINGW32 ~/go/src/github.com/ory/hydra (master)
$ which hydra.exe
/d/Users/S54034/go/bin/hydra.exe

x@x MINGW32 ~/go/src/github.com/ory/hydra (master)
$ hydra.exe help
D:/Users/S54034/go/bin/hydra.exe: error while loading shared libraries: : cannot open shared object file: No such file or directory

x@x MINGW32 ~/go/src/github.com/ory/hydra (master)
$ hydra.exe
D:/Users/S54034/go/bin/hydra.exe: error while loading shared libraries: : cannot open shared object file: No such file or directory

`

**Comment by aburayyanjeffry** [comment]
I've downloaded this

https://github.com/ory/hydra/releases/download/v1.0.0-rc.2%2BoryOS.9/hydra-windows-386.exe

and getting the same error

`x@x MINGW32 ~/Downloads
$ ./hydra-windows-386\ \(1\).exe
D:/Users/S54034/Downloads/hydra-windows-386 (1).exe: error while loading shared libraries: : cannot open shared object file: No such file or directory

`

**Comment by aeneasr** [comment]
1. You don't need minGW
2. I don't think you're running Win32 (386 is 32 bit) unless you're on a 10 year old CPU, you need 64bit (`amd64`)
3. Try (NO MINGW)

```
> go get -d -u github.com/ory/hydra
> cd %GOPATH%/src/github.com/ory/hydra
> set GO111MODULE=on
> go install .
> hydra help
```

**Comment by aburayyanjeffry** [comment]
> 1. You don't need minGW
> 2. I don't think you're running Win32 (386 is 32 bit) unless you're on a 10 year old CPU, you need 64bit (`amd64`)
> 3. Try (NO MINGW)
> 
> ```
> > go get -d -u github.com/ory/hydra
> > cd %GOPATH%/src/github.com/ory/hydra
> > set GO111MODULE=on
> > go install .
> > hydra help
> ```

I'm on 32 bit WinOS because this is the only licensed OS for my machine.

**Comment by aburayyanjeffry** [comment]
> 1. You don't need minGW
> 2. I don't think you're running Win32 (386 is 32 bit) unless you're on a 10 year old CPU, you need 64bit (`amd64`)
> 3. Try (NO MINGW)
> 
> ```
> > go get -d -u github.com/ory/hydra
> > cd %GOPATH%/src/github.com/ory/hydra
> > set GO111MODULE=on
> > go install .
> > hydra help
> ```

`D:\Users\S54034\go\src\github.com\ory\hydra>go get -d -u github.com/ory/hydra
go get: upgrading golang.org/x/crypto@v0.0.0-20171023145632-2509b142fb2b: unreco
gnized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/
crypto?go-get=1: net/http: TLS handshake timeout)
go: finding github.com/asaskevich/govalidator latest
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/beorn7/perks latest
go: finding github.com/Nvveen/Gotty latest
go: finding github.com/Azure/go-ansiterm latest
go: finding github.com/codahale/hdrhistogram latest
go: finding github.com/Microsoft/go-winio v0.4.11
go: finding github.com/docker/go-connections v0.4.0
go: finding github.com/sirupsen/logrus v1.2.0
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/imdario/mergo v0.3.6
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/pborman/uuid v1.2.0
go: finding github.com/go-resty/resty v1.10.2
go: finding github.com/gorilla/context v1.1.1
go: finding github.com/ory/sqlcon v0.0.7
go: finding github.com/rubenv/sql-migrate latest
go: finding golang.org/x/net latest
go: finding github.com/ory/ladon v1.0.0
go: finding golang.org/x/sys latest
go: finding gopkg.in/square/go-jose.v2 v2.1.9
go: finding github.com/prometheus/procfs latest
go: finding github.com/mohae/deepcopy latest
go: finding github.com/spf13/pflag v1.0.3
go: finding gopkg.in/gorp.v1 v1.7.2
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/ory/fosite v0.28.0
go: github.com/go-resty/resty@v1.10.2: parsing go.mod: unexpected module path "g
opkg.in/resty.v1"
go: finding github.com/ory/metrics-middleware v0.0.1
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding github.com/stretchr/objx v0.1.1
go: golang.org/x/crypto@v0.0.0-20180904163835-0709b304e793: unrecognized import
path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=
1: net/http: TLS handshake timeout)
go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33
go: finding github.com/ory/go-convenience v0.1.0
go: finding github.com/spf13/viper v1.2.1
go get: error loading module requirements

D:\Users\S54034\go\src\github.com\ory\hydra>`

got this error when compile in CMD not in GIT-BASH

**Comment by aburayyanjeffry** [comment]
I can't compile without git-hub

`D:\Users\S54034\go\src\github.com\ory\hydra>set GO111MODULE=on

D:\Users\S54034\go\src\github.com\ory\hydra>go clean

D:\Users\S54034\go\src\github.com\ory\hydra>go install
# github.com/ory/hydra/client
client\manager_memory.go:77:26: too many arguments in call to m.Hasher.Hash
        have (context.Context, []byte)
        want ([]byte)
client\manager_memory.go:107:28: too many arguments in call to m.Hasher.Compare
        have (context.Context, []byte, []byte)
        want ([]byte, []byte)
client\manager_memory.go:122:28: too many arguments in call to m.Hasher.Hash
        have (context.Context, []byte)
        want ([]byte)
client\manager_sql.go:361:26: too many arguments in call to m.Hasher.Hash
        have (context.Context, []byte)
        want ([]byte)
client\manager_sql.go:390:28: too many arguments in call to m.Hasher.Compare
        have (context.Context, []byte, []byte)
        want ([]byte, []byte)
client\manager_sql.go:398:25: too many arguments in call to m.Hasher.Hash
        have (context.Context, []byte)
        want ([]byte)
# github.com/ory/hydra/jwk
jwk\jwt_strategy.go:64:32: too many arguments in call to j.RS256JWTStrategy.Hash

        have (context.Context, []byte)
        want ([]byte)
jwk\jwt_strategy.go:73:40: too many arguments in call to j.RS256JWTStrategy.GetS
ignature
        have (context.Context, string)
        want (string)
jwk\jwt_strategy.go:81:36: too many arguments in call to j.RS256JWTStrategy.Gene
rate
        have (context.Context, "github.com/dgrijalva/jwt-go".Claims, "github.com
/ory/fosite/token/jwt".Mapper)
        want ("github.com/dgrijalva/jwt-go".Claims, "github.com/ory/fosite/token
/jwt".Mapper)
jwk\jwt_strategy.go:89:36: too many arguments in call to j.RS256JWTStrategy.Vali
date
        have (context.Context, string)
        want (string)
jwk\jwt_strategy.go:97:34: too many arguments in call to j.RS256JWTStrategy.Deco
de
        have (context.Context, string)
        want (string)

D:\Users\S54034\go\src\github.com\ory\hydra>

`

**Comment by aburayyanjeffry** [comment]
I've manage to compile from cmd. gives the same error. Cant start because DLL is missing

**Comment by aeneasr** [comment]
Which go version do you have installed?

**Comment by aeneasr** [comment]
definitely seems like you don't have go 1.11 installed, please do that - closing
