### ISSUE TITLE
Update Full Stack Example - Version Ory OS.10

### ISSUE THREAD

**Issue by zecarlos94** [ory/examples-archive#28]
With Ory OS.10 is necessary to modify oathkeeper resource server rule(https://github.com/ory/examples/blob/master/full-stack/config/oathkeeper/rules/resource-server.json) in order to use the correct authorizer(Ory Keto): line `"handler": "keto_warden"` should be replaced with line `"handler": "keto_engine_acp_ory"`.

It is also necessary to modify `oathkeeper-proxy` environment in docker-compose.yml(https://github.com/ory/examples/blob/master/full-stack/docker-compose.yml) to set the correct Ory Keto flag. Line `AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466` should be replaced with line `AUTHORIZER_KETO_URL=http://keto:4466`.

Pull Request https://github.com/ory/examples/pull/26 addresses this and other issues.

**Comment by aeneasr** [comment]
Right, I forgot about that PR - I have to check in with the test pipeline and why it fails and once that's done it's ready to merge. If you want to help, it's greatly appreciated.

**Comment by zecarlos94** [comment]
Hi, it's also necessary to update keto.sh(https://github.com/ory/examples/blob/master/scripts/services/keto.sh) to use new Keto commands. Should be set to
`(set -x; keto engines acp ory policies delete --endpoint $url exact $id || true)` and 
`(set -x; keto engines acp ory policies import --endpoint $url exact $filename)`. 

I've checked in your PR and this fix is also there. 

I'm still learning, but I could check your PR (step by step with small modifications and debugging it) as I work with these services.

PS: Without this modification, access tokens were inactive, i.e. after performing token introspection the result was always `{"active":false}` even within expiration date range.

**Comment by aeneasr** [comment]
Thanks, this is really helpful. I didn't  have time to go over this yet though :(

**Comment by zecarlos94** [comment]
Hi,
I've just created a new PR totally based on yours and fixed circleci issues. You can check it and approve it :)
