### ISSUE TITLE
Fullstack example is out of date and fails

### ISSUE THREAD

**Issue by JRAndreassen** [ory/examples-archive#59]
Import fails:
Invalid command in: scripts/services/oathkeeper.sh
configurator_1        | configure stdout | + oathkeeper rules import --endpoint http://oathkeeper-api:4456/ /config/oathkeeper/rules/resource-server.json
configurator_1        | configure stdout | Usage:
configurator_1        |   oathkeeper rules [flags]
configurator_1        |   oathkeeper rules [command]

configurator_1        | Deleting roles in /config/keto/roles/*.json...
configurator_1        | + keto engines acp ory roles delete --endpoint http://keto:4466/ exact '[{' '"id":"admin",' '"members":' '[' '"foo@bar.com",' '"bar@foo.com"' ']' '}]'
keto_1                | time="2020-04-05T13:34:46Z" level=info msg="started handling request" method=DELETE remote="172.21.0.11:33650" request="/engines/acp/ory/exact/roles/%5B%7B"
postgresd_1           | ERROR:  relation "rego_data" does not exist at character 13
postgresd_1           | STATEMENT:  DELETE FROM rego_data WHERE pkey=$1 AND collection=$2
keto_1                | time="2020-04-05T13:34:46Z" level=error msg="An error occurred while handling a request" code=500 debug= details="map[]" error="ERROR: relation \"rego_data\" does not exist (SQLSTATE 42P01)" reason= 
request-id= status=500 writer=JSON
keto_1                | time="2020-04-05T13:34:46Z" level=info msg="completed handling request" measure#keto.latency=1080400 method=DELETE remote="172.21.0.11:33650" request="/engines/acp/ory/exact/roles/%5B%7B" status=500 
text_status="Internal Server Error" took=1.0804ms
configurator_1        | Unable to delete ORY Access Control Policy Role: [DELETE /engines/acp/ory/{flavor}/roles/{id}][500] deleteOryAccessControlPolicyRoleInternalServerError  &{Code:0 Details:[] Message: Reason: Request: 
Status:}
configurator_1        | configure stdout | Unable to delete ORY Access Control Policy Role: [DELETE /engines/acp/ory/{flavor}/roles/{id}][500] deleteOryAccessControlPolicyRoleInternalServerError  &{Code:0 Details:[] Message: Reason: Request: Status:}

keto-migrate_1        | Config file not found because "Config File ".keto" Not Found in "[/]""
keto-migrate_1        | time="2020-04-05T13:34:19Z" level=info msg="Establishing connection with SQL database backend" dsn="postgres://*:*@postgresd:5432/accesscontroldb?sslmode=disable"
keto-migrate_1        | time="2020-04-05T13:34:19Z" level=info msg="Successfully connected to SQL database backend" dsn="postgres://*:*@postgresd:5432/accesscontroldb?sslmode=disable"
keto-migrate_1        | time="2020-04-05T13:34:19Z" level=info msg="Applying storage SQL migrations..."
keto-migrate_1        | panic: runtime error: invalid memory address or nil pointer dereference
keto-migrate_1        | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc82a20]
keto-migrate_1        |
keto-migrate_1        | goroutine 1 [running]:
keto-migrate_1        | github.com/jmoiron/sqlx.(*DB).DriverName(...)
keto-migrate_1        |         /go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/sqlx.go:261
keto-migrate_1        | github.com/ory/keto/storage.(*SQLManager).CreateSchemas(0xc00000e038, 0xc00049d3e0, 0x1d, 0xc0004e20d0, 0x1)
keto-migrate_1        |         /home/ory/storage/manager_sql.go:76 +0x60
keto-migrate_1        | github.com/ory/x/sqlcon.MigratorSQLCmd.func1(0xc0000b62c0, 0xc000412550, 0x1, 0x1)
keto-migrate_1        |         /go/pkg/mod/github.com/ory/x@v0.0.111/sqlcon/migrate.go:71 +0x390
keto-migrate_1        | github.com/spf13/cobra.(*Command).execute(0xc0000b62c0, 0xc000412510, 0x1, 0x1, 0xc0000b62c0, 0xc000412510)
keto-migrate_1        |         /go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x2aa
keto-migrate_1        | github.com/spf13/cobra.(*Command).ExecuteC(0x175e0a0, 0xf397c5, 0x9, 0x0)
keto-migrate_1        |         /go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
keto-migrate_1        | github.com/spf13/cobra.(*Command).Execute(...)
keto-migrate_1        |         /go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
keto-migrate_1        | github.com/ory/keto/cmd.Execute()
keto-migrate_1        |         /home/ory/cmd/root.go:52 +0x31
keto-migrate_1        | main.main()
keto-migrate_1        |         /home/ory/main.go:25 +0x5a
full-stack_keto-migrate_1 exited with code 2

**Comment by aeneasr** [comment]
Thank you, we don't really have time right now to fix these but we welcome any contributions that are going in that direction!
